### ISSUE TITLE
How to format/restore iPod Shuffle 4G?

### ISSUE THREAD

**Issue by skosch** [nims11/IPod-Shuffle-4g#41]
First off, thank you for sharing this absolutely fantastic little script, and I hope I can be forgiven for asking for help here, although this isn't strictly a bug:

This morning, my iPod was "full" – really, the hidden Trash folder was, but I didn't know of its existence at the time. Annoyed and a bit cavalierly, I reformatted the device (as GPT with a single FAT partition). Now I can add files again and run your script without problems. However, when I switch the thing on the LED lights up red and the voice says "Please use iTunes to restore this iPod."

I am hoping that someone might be able to share their partition configuration with me, and chime in with any ideas about what exactly the iPod firmware may be looking for? :bowing_man:

**Comment by NicoHood** [comment]
I made a backup of my initial IPOD. I think you need to use MBR + Fat32, but that is just a blind guess. What is missing are the voiceover files. You can try to connect to someones itunes or contact me via tox and I will share you my zipped files. I think I am not allowed to share them official, because of copyright.

However it would be interesting from where itunes downloads the files (wireshark?) and maybe write a small script that abuses this download. Maybe its just a usb command and the ipod keeps those files internally.

**Comment by skosch** [comment]
I don't have access to anyone with a Mac right now, so I'd be really grateful for those files! How can I add you on tox?

**Comment by NicoHood** [comment]
contact.nicohood.de
