### ISSUE TITLE
aur file should depend on python2-mutagen

### ISSUE THREAD

**Issue by brabalan** [nims11/IPod-Shuffle-4g#47]
The aur file at https://aur.archlinux.org/packages/ipod-shuffle-4g/ depends on mutagen-git, but the the script does not work. You should depend on python2-mutagen

**Comment by nims11** [comment]
Assigning @NicoHood who maintains the AUR package.

**Comment by NicoHood** [comment]
It does not depend on mutagen-git directly, but mutagen (for python2) was removed from the official repositories. Also this issue was already reported and does not belong to this bugtracker.

@nims11 We should switch to python3 now. Python3 support is already implemented, we just need to review it once again and then merge the PR: https://github.com/nims11/IPod-Shuffle-4g/pull/34

**Comment by brabalan** [comment]
@NicoHood Thank you for the information. I did not know the issue was reported. Maybe a link to where to report issues regarding the aur file could be added to the README.

**Comment by NicoHood** [comment]
aur issues belong to the aur. via comments, as usual. the aur in general has nothing to do with the software itself. In this case I maintain the software and the AUR package, but anyways the usual way is to flag aur issues on the aur ;-)
