### ISSUE TITLE
Question for usuage of the tool

### ISSUE THREAD

**Issue by ghost** [nims11/IPod-Shuffle-4g#68]
Hi everyone, I'm sorry for making an extra issue for this.  
I just wanted to ask, if that is the right way to use the tool:  

- I plug in my iPod Shuffle (4th Gen) & put all my mp3-files in the root directory
- Then I execute the script by also specifying the path to the root directory of the iPod  

Also do I need to keep the mp3-files in the root directory after the script ran through or can I remove them?  
Sorry those questions might be obvious to many people, it's just for my understanding.

**Comment by harjitmoe** [comment]
> Also do I need to keep the mp3-files in the root directory after the script ran through

Yes (although they don't necessarily have to be in the root directory—you'd need to re-run the script if they are moved/renamed though).

The script basically indexes the iPod so that the iPod firmware knows where the MP3s are (and generates the voice-over files for the song/playlist names if you're using that part)—it doesn't copy the MP3s anywhere.

**Comment by ghost** [comment]
Ahh ok, I see.
Thanks so much for the explanation, this tool is a life-saver! ^^
