### ISSUE TITLE
Adding WMA support

### ISSUE THREAD

**Issue by OursDesCavernes** [nims11/IPod-Shuffle-4g#9]
Patch in PR #7 enables WMA file listing. This works with my iPod 4G.

**Comment by nims11** [comment]
I'll test and merge it asap

**Comment by NicoHood** [comment]
```
Audio formats supported: AAC (8 to 320 Kbps), Protected AAC (from iTunes Store), MP3 (8 to 320 Kbps), MP3 VBR, Audible (formats 2, 3, 4, Audible Enhanced Audio, AAX, and AAX+), Apple Lossless, AIFF, and WAV
````

From here:
https://www.apple.com/ipod-shuffle/specs/

But we could be combine this with https://github.com/nims11/IPod-Shuffle-4g/issues/11 and with a correct encoder the wav could be automatic converted into mp3 or so.

**Comment by NicoHood** [comment]
Also it looks that there is no much room for other filetypes. However "3" seems to be unknown. Might be .aa, but we could test this with an official itunes program, that I do not have.

https://github.com/nims11/IPod-Shuffle-4g/blob/master/docs/iTunesSD3gen.md#trackx

**Comment by nims11** [comment]
I think .aa is aac (?). Anyway, I will sync up a test db from itunes when I boot into windows and then we will see.

**Comment by NicoHood** [comment]
If you do have windows, could you please create a music library with 2 (different) songs where both songs are in a playlist, each? It would be nice if you can use some public available songs (like the world of goo soundtrack).

Since I am not able to run itunes in a vm (have several windows problems and gave up), this would be nice to compare with. If you then can post a clean setup with those 2 files and playlists, that'd be nice. You can pack the whole ipod as zip or xdd all hexdumps via gist.github.com. This would help me to debug most features, as I can compare then with itunes.

I think we can also complete the docs even more. In Itunes you can set some other general setting which might be saved in different databases, we do not manipulate yet (like sound limit maybe). Finding out more about this would be nice as well.

**Comment by NicoHood** [comment]
Can you please provide an .aa testfile generated with itunes?

**Comment by NicoHood** [comment]
It seems wma is a container and a codec at the same time. Your files might be incompatible while his are. Or he has missnamed wav files.
https://en.wikipedia.org/wiki/Windows_Media_Audio#Codecs

Since the situation is unclear and not all wma file work and also apple doesnt officially support it and the script is made for linux and not micro$$$$ users I suggest to close the PR and the issue. The best idea is to just convert those files.

**Comment by nims11** [comment]
Unclear WMA support. Better just convert it to other formats.
